/* This file is auto-generated by SST. Do not edit. */
/* Run `npx sst dev` or `npx sst deploy` to regenerate. */

declare module "sst" {
  export interface Resource {
    AdonaUI: {
      type: "sst.aws.Nextjs";
      url: string;
    };
    UserPool: {
      id: string;
      type: "sst.aws.CognitoUserPool";
    };
    Web: {
      id: string;
      secret: string;
      type: "sst.aws.CognitoUserPoolClient";
    };
  }
}
