/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

import "sst"
declare module "sst" {
  export interface Resource {
    "Adona": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "ToolRunner": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ToolsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "UserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "Web": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
    "WorkflowOrchestrator": {
      "name": string
      "type": "sst.aws.Function"
    }
    "WorkflowStepRunner": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}

import "sst"
export {}